addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 18c09ebc-b907-4603-b27e-7b08ceda1004
after_script:
- ./travisupload.sh
- ./travism2_upload.sh
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq s3cmd
- ./make_s3cfg.sh
- sh -e /etc/init.d/xvfb start
- ./travism2_install.sh
- ./travisgetkeystore.sh
before_script:
- if [ "$PYDEV_TEST" == "true" ]; then git apply --whitespace=nowarn test_with_tycho.patch;
  fi
- if [ "$PYDEV_TEST" == "true" ]; then ./travisdeps.sh; fi
branches: ''
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - DISPLAY=:99.0
  - ARTIFACTS_S3_BUCKET=pydevbuilds2
  - ARTIFACTS_AWS_REGION=us-east-1
  - secure: U9AGWmSTwqa2DrmDSBZX6lHkXkSBkxnToj2QtEe3oZmcJYrMi5lX2I4SWMgBu08GCjkBLi4ztRvfoVyE+L5G90QN8Q2+FQNMnoX+mDzcVBOBuFEZBIOBnFrAfGDtYJl0OnTRezZMJY1hk8pBuF8qBSytCNYT7Pz7lDg94o+Oxn0=
  - secure: Pfq+chN3NUoFhPXDdFoksEYZdJjmtFctdSQksaY+c/YbfFmWAe/8VMekj01IiFeNIFz3WoissaYvF/knJFaJl6VCJY825rwHWuTD2eCSYbpTXLE4n0K9WO63I4dpWrXlMREFmn4M5bcA7KNuIbQSFv2Tdhhmk/gZQTW45uTXNXo=
  - PYDEV_TEST_PLATFORM=travis
  - SIGN_KEYSTORE=~/pydev.keystore
  - SIGN_ALIAS=kc_eclipse
  - secure: T6mFt4Gn2ix6OowWbMtSG0skKf27WoaQCxy0s+q1rBTF1FN8zJARveAR2hpvjcyRDBeQdCynvZWL7sawQL7xzUUniCsfFtpHl7fro66IzhIBZGkS8Ra/wprGOxQ56ZCNB/QJ3f7gnisrQg+G2mhlV1U7RsBMNYfRdKsOUwJ0wXs=
  - secure: V62QbNAT4SfRSUUEE1nlpx9UmjBnW54SnMf+ZR4stM+kBZxZUT7u3XatOABNupb052xJTYGISEjPqXDZ4VqOjM6fUu902LOCCZ0U1ojyOUdpai2gFz2ajtMTzg7MFXFFuYytZ9KRSalKLOzRylXroZVJK7DUtC9NMih6dCANvbA=
  matrix:
  - PYDEV_TEST=true
  - PYDEV_TEST=false
install:
- ./mvnts.sh install -Dtycho.localArtifacts=ignore -DskipTests=true -B
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=18c09ebc-b907-4603-b27e-7b08ceda1004
script:
- if [ "$PYDEV_TEST" == "true" ]; then ./mvnts.sh integration-test -B; fi
# Modified by Insights Service at 2016-12-27 10:49:18.943169
